set fallback := true

run:
    DEBUG=TRUE python main.py

test:
    curl -f \
        -X POST \
        -F "file=@$PATH_AUDIO/1272-135031-0014.wav"  \
        --output tmp.json \
        localhost:8081

test_all:
    #!/usr/bin/env bash
    for file in $(ls $PATH_AUDIO/* | head -n 10); do
      echo $file
      ((curl -s --fail-with-body \
          -X POST \
          -F "file=@$file"  \
          --output tmp.json \
          localhost:8081 && echo "Ok for $file") || echo "Failed for $file")&
    done
    wait
