set fallback

_default:
	@just --list

pre_commit: check clippy
	cargo fmt

clippy:
	cargo clippy --fix --allow-staged --allow-dirty  -- -A clippy::let_unit_value -D warnings

check:
	cargo check
	cargo check --features jaeger

docker_load features="no-telemetry":
	echo "Buidlding with features {{features}}"
	$(nix build .#fn_echo_{{features}} --print-out-paths --no-link --quiet) | docker load

run:
	#!/usr/bin/env bash
	export SLA='{
		"id": "e0d59045-ff5a-4354-828d-7b0c5119aeb8",
		"memory": "50 MB",
		"cpu": "50 millicpu",
		"latencyMax": "10 ms",
		"maxReplica": 1,
		"duration": "120 seconds",
		"functionImage": "ghcr.io/volodiapg/giraff:fn_echo",
		"functionLiveName": "debug",
		"dataFlow": [],
		"envVars": []
	}'
	export ID="toto"

	export RUST_LOG="warn,echo=trace"
	cargo run
