DOCKER := "podman"

_default:
    @just --list

# Run the echo server
run $SERVER_PORT="30080":
	cargo run

# Build the project as a docker image
container:
    {{DOCKER}} build --target iot_emulation-default -t iot_emulation:latest .

# Push an image to ghcr
_push image user:
    {{DOCKER}} tag {{image}} ghcr.io/{{user}}/{{image}}
    {{DOCKER}} push ghcr.io/{{user}}/{{image}}

# Push docker images to ghcr
ghcr user: container
    just _push iot_emulation:latest {{user}}

check:
    cargo check
    cargo check --features jaeger