set fallback := true

# -F "file=@toto.jpg" \
test:
    curl \
        -X POST \
        -F "file=@$PATH_IMAGE/n03417042_29361.JPEG"  \
        --output tmp.jpeg \
        localhost:8081

test_all:
    #!/usr/bin/env bash
    for file in $(ls $PATH_IMAGE/*.JPEG | head -n 10); do
        echo $file
        (curl -s --fail-with-body \
            -X POST \
            -F "file=@$file"  \
            --output tmp.jpeg \
            localhost:8081 || echo "Failed for $file")&
    done
    wait
