# Runs the script
_default: make

make:
    mkdir ./cache || true
    mkdir ./figures || true
    mkdir ./out || true
    @echo -e "\033[1;33mstarting...\033[0m" >> logs.fifo
    Rscript make.R || (echo -e "\033[1;31mERR\033[0m" >> logs.fifo ; false)
    @echo -e "\033[1;32mdone\033[0m"
    @echo -e "\033[1;32mdone\033[0m" >> logs.fifo

make_export:
  nix develop .#mining-export -c just make

# export:
#     nix develop .#mining-export -c just watch

logs:
  mkfifo logs.fifo || true
  tail -f logs.fifo

# Serves the content of the directory so graphs can be opened in a browser
serve port="9000":
    browser-sync start --config ./bs-config.js

pub:
    #!/usr/bin/env bash
    commands=( \
      "binserve" \
      "sudo tailscale funnel 9003" \
    )
    parallel -j2 --will-cite --tty ::: "${commands[@]}"

watch:
    ls **/*.R *.R | entr -nr just
