# Runs the script
run:
    @mkdir -p /tmp/R-giraff
    @ln -s /tmp/R-giraff ./cache || true
    mkdir -p /tmp/R-giraff-out
    ln -s /tmp/R-giraff-out ./out || true
    @echo -e "\033[1;33mstarting...\033[0m" | ncat localhost 4001
    Rscript main.R || (echo -e "\033[1;31mERR\033[0m" | ncat localhost 4001 ; false)
    @echo -e "\033[1;32mdone\033[0m"
    @echo -e "\033[1;32mdone\033[0m" | ncat localhost 4001

export:
    nix develop .#mining-export -c just watch

logs:
    #! /usr/bin/env bash
    touch logs.txt
    while true; do
      ncat -l 4001 | tee -a logs.txt
    done

# Serves the content of the directory so graphs can be opened in a browser
serve port="9000":
    browser-sync start --config ./bs-config.js

pub:
    #!/usr/bin/env bash
    commands=( \
      "binserve" \
      "sudo tailscale funnel 9003" \
    )
    parallel -j2 --will-cite --tty ::: "${commands[@]}"

watch:
    ls *.R | entr -nr just
