pre_commit: check clippy
	cargo fmt

clippy:
	cargo clippy --fix --allow-staged --allow-dirty  -- -A clippy::let_unit_value -D warnings

check:
	cargo check
	cargo check --features jaeger

run:
	#!/usr/bin/env bash
	export SLA='{
		"id": "e0d59045-ff5a-4354-828d-7b0c5119aeb8",
		"memory": "50 MB",
		"cpu": "50 millicpu",
		"latencyMax": "10 ms",
		"maxReplica": 1,
		"duration": "120 seconds",
		"functionImage": "ghcr.io/volodiapg/echo:latest",
		"functionLiveName": "debug",
		"dataFlow": []
	}'
	export INFLUX_ADDRESS="127.0.0.1:9086"
	export INFLUX_TOKEN="xowyTh1iGcNAZsZeydESOHKvENvcyPaWg8hUe3tO4vPOw_buZVwOdUrqG3gwV314aYd9SWKHcxlykcQY_rwYVQ=="
	export INFLUX_ORG="faasfog"
	export INFLUX_BUCKET="faasfog"

	export RUST_LOG="warn,echo=trace"
	cargo run

# faas target:
# 	#!/usr/bin/env bash
# 	export DOCKER_BUILDKIT=1 faas-cli build -f ./{{target}}.yml
# 	faas-cli push -f ./{{target}}.yml
