# Entrypoint, run deploy and then tunnels
_default:
    @just --choose
    
build-iso:
    nix build .#nixosConfigurations.isoimage.config.system.build.isoImage

build-vm:
    nix build .#qcow2

upload $CITY="nancy":
    rsync --perms --chmod=u+rwx,g+rwx,o+rwx result/nixos*.qcow2 $CITY.g5k:~/nixos.qcow2
    
vm :
    export QEMU_NET_OPTS="hostfwd=tcp::2221-:22,hostfwd=tcp::8080-:80" && \
    nixos-rebuild --flake .#isoimage build-vm && \
    ./result/bin/run-*-vm
