/* 
 * OpenFaaS API Gateway
 *
 * OpenFaaS API documentation
 *
 * OpenAPI spec version: 0.8.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Info {
  /// The OpenFaaS Provider
  #[serde(rename = "provider")]
  provider: Value,
  /// Version of the Gateway
  #[serde(rename = "version")]
  version: Value,
  /// Platform architecture
  #[serde(rename = "arch")]
  arch: Option<String>
}

impl Info {
  pub fn new(provider: Value, version: Value) -> Info {
    Info {
      provider: provider,
      version: version,
      arch: None
    }
  }

  pub fn set_provider(&mut self, provider: Value) {
    self.provider = provider;
  }

  pub fn with_provider(mut self, provider: Value) -> Info {
    self.provider = provider;
    self
  }

  pub fn provider(&self) -> &Value {
    &self.provider
  }


  pub fn set_version(&mut self, version: Value) {
    self.version = version;
  }

  pub fn with_version(mut self, version: Value) -> Info {
    self.version = version;
    self
  }

  pub fn version(&self) -> &Value {
    &self.version
  }


  pub fn set_arch(&mut self, arch: String) {
    self.arch = Some(arch);
  }

  pub fn with_arch(mut self, arch: String) -> Info {
    self.arch = Some(arch);
    self
  }

  pub fn arch(&self) -> Option<&String> {
    self.arch.as_ref()
  }

  pub fn reset_arch(&mut self) {
    self.arch = None;
  }

}



