default:
    #!/usr/bin/env bash
    OLD_EXPE_LOAD_FILE="${EXPE_LOAD_FILE:-}"
    OLD_EXPE_SAVE_FILE="${EXPE_SAVE_FILE:-}"
    OLD_PATH="$PATH"
    source ../env_checkpoint.env.local.sh
    PATH="$PATH:$OLD_PATH"
    export EXPE_LOAD_FILE="$OLD_EXPE_LOAD_FILE"
    export EXPE_SAVE_FILE="$OLD_EXPE_SAVE_FILE"
    export COLLECTOR_URL=127.0.0.1:4317
    export DURATION_MULTIPLIER=1
    export ARRIVAL_REQUEST_MULTIPLIER=1
    export FUNCTION_MIN_DURATION=1000
    go run main.go

test experiments_dotfile="../.experiments.env" env_variation="../.env.dev":
    #!/usr/bin/env bash
    set -o allexport
    source ../.env
    source {{ experiments_dotfile }}
    source {{ env_variation }}
    set +o allexport
    export TARGET_NODE_NAMES=toto
    export TARGET_NODES=toto
    export EXPE_SAVE_FILE=toto.txt
    go run main.go


