default:
    #!/usr/bin/env bash
    OLD_EXPE_LOAD_FILE="${EXPE_LOAD_FILE:-}"
    OLD_EXPE_SAVE_FILE="${EXPE_SAVE_FILE:-}"
    OLD_PATH="$PATH"
    source ../env_checkpoint.env.local.sh
    PATH="$PATH:$OLD_PATH"
    export EXPE_LOAD_FILE="$OLD_EXPE_LOAD_FILE"
    export EXPE_SAVE_FILE="$OLD_EXPE_SAVE_FILE"
    export COLLECTOR_URL=127.0.0.1:4317
    export DURATION_MULTIPLIER=125000
    export ARRIVAL_REQUEST_MULTIPLIER=25000
    go run main.go
