RUN := "poetry run python ./grid5000-build.py"
GHCR_USER := "volodiapg"

# Default action whithout a verb provided
_default:
  @just --choose

# Build the docker image and upload it to github (uses grid5000)
build:
   {{RUN}} up
   {{RUN}} upload
   {{RUN}} build
   {{RUN}} download
   {{RUN}} ghcr --user {{GHCR_USER}}

# Clean locally and grid5000
clean:
  {{RUN}} clean
  rm -rf enos_* current cachedir
