name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.inria.fr/magellan/giraff_fog_at_scale"
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "gitlab.inria.fr"
        GITLAB_USERNAME: "vparolgu"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} # Generate here: https://gitlab.com/profile/personal_access_tokens
        GITLAB_PROJECT_ID: "59132" # https://gitlab.com/<namespace>/<repository>/edit
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
